### ISSUE TITLE
Question/Issue during install and abend of githubutil

### ISSUE THREAD

**Issue by plingafelt** [kevinkahn/softconsole#9]
Hello.  Thank you again for sharing your code.  It has helped tremendously with the Wife Acceptance Factor (WAF) of my home automation hobby.  Recently, I decided to rebuild our console (and add a second).  I was trying to run the install scripts and it's not working.

The main culprit seems to be an issue in githubutil.py and the setup of or movement to the consolestable directory.  

********Start log excerpt*******
*** Setupconsole ***
Created: Console
Created: consolestable
Created: consolebeta
Created: consolerem
Created: consoledev
Traceback (most recent call last):
  File "setupconsole.py", line 36, in <module>
    U.StageVersion('consolestable', 'currentrelease', 'Initial Install')
  File "/home/pi/githubutil.py", line 25, in StageVersion
    os.chdir(vdir)
FileNotFoundError: [Errno 2] No such file or directory: 'consolestable'
cp: cannot stat 'consolestable/scripts/python-sudo.sh': No such file or directory
chmod: cannot access 'python-sudo.sh': No such file or directory
mv: cannot move 'Consoleauth' to 'Console/cfglib/auth.cfg': No such file or directory

----------------------------------------------------------
----------------------------------------------------------
Set No Console Autostart at Boot
Mon 18 Nov 07:21:06 EST 2019
----------------------------------------------------------
----------------------------------------------------------

----------------------------------------------------------
----------------------------------------------------------
Enable VNC
Mon 18 Nov 07:21:06 EST 2019
----------------------------------------------------------
----------------------------------------------------------
Created symlink /etc/systemd/system/multi-user.target.wants/vncserverpi.service → /usr/lib/systemd/system/vncserverpi.service.
rm: cannot remove 'tmp': No such file or directory
mv: cannot stat 'doinstall.sh': No such file or directory
mv: cannot stat 'di.log': No such file or directory

----------------------------------------------------------
----------------------------------------------------------
Install and setup finished
Mon 18 Nov 07:21:08 EST 2019
----------------------------------------------------------
----------------------------------------------------------
*******End Log excerpt*******

The install finished up but leaves the consolestable directory empty.
This install is on a pi3 with a pi7 screen.  Fresh install of Buster, move ssh and piesetup.sh scripts to boot, ssh in to Pi and run.  so very vanilla.  Everything passes up to this point with no errors. 

I also noticed in line 107 of installconsole.sh that there is an $ in front of InstallBeta (   Get_yn $InstallBeta "Download beta also? (Y/N)?" ) which I think would cause an error if you opt to include the Beta, but isn't a show stopper in the overall scheme of things.  

Finally, installconsole.sh also has a section on Wheezy install at line 152 which was throwing an exception for me because I don't think the vairable for $UserWheezy was populated.  The scripts just moved on, and since I didn't need it, I think it's fine.  Just an FYI.

**Comment by kevinkahn** [comment]
Arg!  My bad.  I had added some failsafe code to the install process and got the indentation wrong on one line so the install was trying to get into a non-existent directory.  I must not have actually done a complete install myself since that change.   I'm not at home so can't really test the fix but it looked pretty obvious so I pushed a new currentrelease version which should work for you.  Try the install again from the beginning and it should be pulling the fixed version.

Thanks for noting the other two script items.  The Wheezy stuff should just go away as it is an historical artifact so for the moment I commented it out.  Also fixed the InstallBeta deal though generally that doesn't see use.   Let me know if this fixes things for you.  (Definitely understand the WAF impact as it helps keep my hobby acceptable as well. :-) )

Kevin

**Comment by plingafelt** [comment]
Sorry for not getting back to you last night and THANK YOU for such a quick response.  This seems to have done the trick.  The install ran through and created the simple example system.  So I should be good to update the weather provider info and put my old config files back.  Thanks a ton.
